import type { NewsCard } from '@/types'

export const SUGGESTIONS = [
  { label: 'Latest LLM benchmarks',          prompt: 'What are the latest LLM benchmarks?' },
  { label: 'Frontier model releases this week', prompt: 'Walk me through frontier model releases this week.' },
  { label: 'AI policy in the EU',             prompt: 'Catch me up on AI policy in the EU.' },
  { label: 'Open vs. closed models',          prompt: 'Where does the open-vs-closed model debate stand right now?' },
]

export const TOPIC_SUGGESTIONS: Record<string, { label: string; prompt: string }> = {
  ai_ml:     { label: 'Latest AI & ML news',              prompt: 'What are the latest AI and ML developments this week?' },
  cyber:     { label: 'Cybersecurity threats',            prompt: 'What are the biggest cybersecurity stories right now?' },
  cloud:     { label: 'Cloud & infrastructure updates',   prompt: 'What\'s new in cloud and infrastructure this week?' },
  softdev:   { label: 'Software development trends',      prompt: 'What are the most important software development trends right now?' },
  hardware:  { label: 'Chips & hardware news',            prompt: 'What\'s happening in chips and hardware this week?' },
  privacy:   { label: 'Data & privacy updates',           prompt: 'What are the latest data privacy developments?' },
  quantum:   { label: 'Quantum computing progress',       prompt: 'What\'s new in quantum computing?' },
  robotics:  { label: 'Robotics & automation news',       prompt: 'What are the latest robotics and automation stories?' },
  fintech:   { label: 'Fintech & payments news',          prompt: 'What\'s happening in fintech and payments this week?' },
  health:    { label: 'Health & biotech updates',         prompt: 'What are the biggest health tech and biotech stories?' },
  cleantech: { label: 'Clean tech & sustainability',      prompt: 'What\'s new in clean tech and sustainability?' },
  space:     { label: 'Space & satellite updates',        prompt: 'What\'s the latest in space and satellite technology?' },
  xr:        { label: 'Metaverse & XR news',              prompt: 'What\'s new in metaverse and XR this week?' },
  ma:        { label: 'M&A & funding rounds',             prompt: 'What are the biggest M&A deals and funding rounds this week?' },
  ipo:       { label: 'IPO & market news',                prompt: 'What\'s happening in tech IPOs and markets?' },
  bigtech:   { label: 'Big Tech news',                    prompt: 'What are the biggest stories from FAANG and Microsoft this week?' },
  startups:  { label: 'Startups & venture capital',       prompt: 'What are the most interesting startup and VC stories right now?' },
  layoffs:   { label: 'Layoffs & hiring trends',          prompt: 'What\'s happening with tech layoffs and hiring?' },
  earnings:  { label: 'Earnings & revenue updates',       prompt: 'What are the latest tech earnings and revenue results?' },
  ai_reg:    { label: 'AI regulation news',               prompt: 'What\'s new in AI regulation and policy?' },
  gdpr:      { label: 'Data protection updates',          prompt: 'What are the latest GDPR and data protection developments?' },
  antitrust: { label: 'Antitrust & competition',          prompt: 'What\'s happening in tech antitrust and competition cases?' },
  exports:   { label: 'Export controls & sanctions',      prompt: 'What are the latest export controls affecting tech?' },
  digiinfra: { label: 'Digital infrastructure policy',   prompt: 'What\'s new in digital infrastructure policy?' },
  cyberpol:  { label: 'Cybersecurity policy',            prompt: 'What\'s happening in cybersecurity policy and regulation?' },
  platform:  { label: 'Platform regulation news',        prompt: 'What are the latest platform regulation developments?' },
}

export const BENCHMARK_CARDS: NewsCard[] = [
  {
    id: 'c1', source: 'Artificial Analysis', time: '2h ago', kind: 'Benchmark', tone: 'lead', tag: 'Reasoning',
    title: 'GPT-5.1 edges Claude 4.5 on reasoning, trails on long-context recall',
    blurb: 'On the latest combined index, GPT-5.1 takes the lead on math and code, while Claude 4.5 holds long-context retrieval and tool-use. Gemini 3 closes the gap.',
  },
  {
    id: 'c2', source: 'LMSys Arena', time: '5h ago', kind: 'Leaderboard', tone: 'calm', tag: 'Open weights',
    title: 'Open-weights climb: Llama 4.1 enters Arena top five for the first time',
    blurb: 'Crowd-rated head-to-head puts Meta\'s Llama 4.1 within 18 Elo of the leading closed model. DeepSeek-R2 and Qwen 3 follow closely behind.',
  },
  {
    id: 'c3', source: 'MMLU-Pro', time: 'Yesterday', kind: 'Analysis', tone: 'calm', tag: 'Saturation',
    title: 'Saturation watch: top scores cluster within two points',
    blurb: 'Five frontier models now score within a narrow band on MMLU-Pro. Researchers argue the benchmark is approaching its ceiling and call for harder evals.',
  },
  {
    id: 'c4', source: 'SWE-bench Verified', time: 'Yesterday', kind: 'Coding', tone: 'calm', tag: 'Agents',
    title: 'Agentic coding scores jump 11 points after new tool-use protocol',
    blurb: 'After adopting a standardized tool-use schema, three frontier models posted double-digit gains on real-world software engineering tasks.',
  },
]

export const CARD_ACTIONS = [
  { id: 'report',  label: 'Make a report',   icon: 'doc' },
  { id: 'compare', label: 'Compare models',  icon: 'compare' },
  { id: 'explore', label: 'Explore deeper',  icon: 'compass' },
  { id: 'save',    label: 'Save thread',     icon: 'bookmark' },
]

export const FOLLOWUPS = [
  'Which benchmarks should I actually trust?',
  'How is GPT-5.1 different from Claude 4.5 in practice?',
  'Show me the open-weights leaderboard.',
  'Draft me a one-page summary I can share.',
]

export const NEWS_BY_TOPIC: Record<string, NewsCard[]> = {
  ai_ml: [
    { id: 'ai1', source: 'The Verge', time: '1h ago', kind: 'Release', tone: 'lead', tag: 'Models',
      title: 'Anthropic ships Claude 4.5 with expanded tool use and 200k context',
      blurb: 'The new model leads on long-context recall and agentic benchmarks, while GPT-5.1 still edges it on pure reasoning tasks. Pricing unchanged.' },
    { id: 'ai2', source: 'Hugging Face Blog', time: '3h ago', kind: 'Research', tone: 'calm', tag: 'Open weights',
      title: 'Llama 4.1 enters the Arena top five — first open model to do so',
      blurb: 'Meta\'s latest open release closes to within 18 Elo of the leading closed model on crowd-rated head-to-head evaluations.' },
  ],
  hardware: [
    { id: 'hw1', source: 'Reuters', time: '2h ago', kind: 'Chips', tone: 'lead', tag: 'NVIDIA',
      title: 'NVIDIA Blackwell GB300 enters mass production ahead of schedule',
      blurb: 'TSMC confirmed GB300 wafer starts are running two weeks early, lifting analyst estimates for Q3 data-center revenue by ~8%.' },
    { id: 'hw2', source: 'AnandTech', time: '6h ago', kind: 'Analysis', tone: 'calm', tag: 'AMD',
      title: 'AMD MI400X spec leak: 384 GB HBM4, 3.2 TB/s bandwidth',
      blurb: 'Leaked slides put MI400X ahead of H200 on memory bandwidth. Analysts caution that software stack maturity remains the real differentiator.' },
  ],
  cyber: [
    { id: 'cy1', source: 'Krebs on Security', time: '45m ago', kind: 'Breach', tone: 'lead', tag: 'Ransomware',
      title: 'LockBit 4.0 targets European healthcare: 3 hospitals offline',
      blurb: 'A new LockBit variant exploited an unpatched Citrix Gateway to encrypt records across three Dutch hospital networks. Negotiations ongoing.' },
    { id: 'cy2', source: 'CISA Advisory', time: '4h ago', kind: 'Vuln', tone: 'calm', tag: 'Zero-day',
      title: 'CISA adds Windows Kernel zero-day to KEV catalog — patch now',
      blurb: 'CVE-2026-1337 allows local privilege escalation with no user interaction. Microsoft released an out-of-band patch; CISA mandates federal agency remediation by June 7.' },
  ],
  privacy: [
    { id: 'pr1', source: 'POLITICO', time: '2h ago', kind: 'Regulation', tone: 'lead', tag: 'GDPR',
      title: 'Meta fined €1.3B — largest GDPR penalty on record — over EU-US transfers',
      blurb: 'Ireland\'s DPC ruled that Meta\'s standard contractual clauses fail to adequately protect EU data sent to US servers. Meta has 12 months to wind down transfers.' },
    { id: 'pr2', source: 'TechCrunch', time: '5h ago', kind: 'Policy', tone: 'calm', tag: 'Privacy',
      title: 'US Senate advances American Privacy Rights Act with bipartisan support',
      blurb: 'The bill would create a federal right to data deletion and opt-out of targeting, pre-empting state laws like CCPA. Final vote expected next week.' },
  ],
  cloud: [
    { id: 'cl1', source: 'AWS Blog', time: '1h ago', kind: 'Launch', tone: 'lead', tag: 'Infrastructure',
      title: 'AWS launches 5 new Availability Zones in Southeast Asia and LATAM',
      blurb: 'New AZs in Jakarta, Kuala Lumpur, and São Paulo extend AWS\'s low-latency footprint to 35 regions globally ahead of competitors.' },
    { id: 'cl2', source: 'The Register', time: '3h ago', kind: 'Outage', tone: 'calm', tag: 'Azure',
      title: 'Azure West Europe incident: 90-min degradation for CosmosDB customers',
      blurb: 'A misconfigured DNS change triggered cascading latency spikes across West Europe. Microsoft confirmed full recovery at 09:42 UTC.' },
  ],
  ma: [
    { id: 'ma1', source: 'Bloomberg', time: '30m ago', kind: 'M&A', tone: 'lead', tag: 'Acquisition',
      title: 'Google acquires AI safety lab Conjecture for $1.4B',
      blurb: 'The deal gives Google access to Conjecture\'s interpretability research team and proprietary alignment tooling. Regulatory review expected to take 6–9 months.' },
    { id: 'ma2', source: 'PitchBook', time: '4h ago', kind: 'Funding', tone: 'calm', tag: 'Series B',
      title: 'Mistral AI closes $640M Series B at $6B valuation',
      blurb: 'General Catalyst led the round, which Mistral will use to expand compute, open-source releases, and its Paris engineering office.' },
  ],
  bigtech: [
    { id: 'bt1', source: 'CNBC', time: '2h ago', kind: 'Earnings', tone: 'lead', tag: 'Microsoft',
      title: 'Microsoft Q3: Copilot contributes $3.2B to cloud revenue, beating estimates',
      blurb: 'Azure grew 31% YoY, driven by AI workloads. CFO Amy Hood raised full-year guidance by $400M, citing enterprise Copilot seat growth.' },
    { id: 'bt2', source: 'The Information', time: '5h ago', kind: 'Strategy', tone: 'calm', tag: 'Apple',
      title: 'Apple delays on-device LLM to iOS 20 — Siri overhaul pushed back again',
      blurb: 'Engineering challenges with the 3B-parameter model\'s memory footprint on iPhone 15 chips forced a one-year delay. iOS 19 will ship a smaller, more limited assistant.' },
  ],
  startups: [
    { id: 'st1', source: 'TechCrunch', time: '1h ago', kind: 'Funding', tone: 'lead', tag: 'Unicorn',
      title: 'Cognition (Devin AI) raises $200M Series B, now valued at $2B',
      blurb: 'The autonomous software engineering startup tripled its valuation in 6 months. It claims Devin completes 30% of GitHub issues end-to-end without human input.' },
    { id: 'st2', source: 'Sifted', time: '4h ago', kind: 'Startup', tone: 'calm', tag: 'Europe',
      title: 'Berlin-based Aleph Alpha pivots to enterprise sovereign AI — fires 40',
      blurb: 'Facing pressure from open-weight giants, Aleph Alpha is repositioning as a provider of on-premises AI for European governments and regulated industries.' },
  ],
  ai_reg: [
    { id: 'ar1', source: 'Euractiv', time: '1h ago', kind: 'Policy', tone: 'lead', tag: 'EU AI Act',
      title: 'EU AI Act general-purpose model rules enter force June 1',
      blurb: 'Providers of models above 10^25 FLOPs must now submit technical documentation to AISI. Companies with models over 10^26 FLOPs face mandatory red-teaming.' },
    { id: 'ar2', source: 'FT', time: '5h ago', kind: 'Regulation', tone: 'calm', tag: 'US',
      title: 'Biden AI executive order successor signed — federal agencies must audit AI systems',
      blurb: 'The new order requires all federal agencies using AI in consequential decisions to publish impact assessments by September 2026.' },
  ],
  softdev: [
    { id: 'sd1', source: 'GitHub Blog', time: '2h ago', kind: 'Tool', tone: 'lead', tag: 'Copilot',
      title: 'GitHub Copilot now suggests full PR descriptions and test plans',
      blurb: 'The new "Copilot Workspace" feature drafts issue-to-PR flows autonomously, reducing average PR review time by 18% in internal Microsoft trials.' },
    { id: 'sd2', source: 'InfoQ', time: '6h ago', kind: 'Language', tone: 'calm', tag: 'Rust',
      title: 'Rust officially recommended for Linux kernel new drivers — C still default',
      blurb: 'Linus Torvalds endorsed Rust for new subsystem drivers in a LKML post, calling it "clearly safer" for memory management in isolated components.' },
  ],
  fintech: [
    { id: 'ft1', source: 'Reuters', time: '2h ago', kind: 'Payments', tone: 'lead', tag: 'Stablecoin',
      title: 'Stripe adds USDC settlement — merchants can now receive payouts in stablecoin',
      blurb: 'Stripe\'s new stablecoin payout option targets gig-economy platforms and cross-border merchants in 47 countries, bypassing traditional FX rails.' },
    { id: 'ft2', source: 'Finextra', time: '5h ago', kind: 'Banking', tone: 'calm', tag: 'Open banking',
      title: 'UK mandates open banking for A2A payments by Q4 2026',
      blurb: 'The FCA\'s updated roadmap requires all UK banks to support account-to-account payment initiation for third-party apps, challenging card network dominance.' },
  ],
  quantum: [
    { id: 'qu1', source: 'Nature', time: '3h ago', kind: 'Research', tone: 'lead', tag: 'Error correction',
      title: 'Google achieves logical qubit error rate below 10⁻⁶ — a key threshold',
      blurb: 'The Willow chip team demonstrated sustained error rates low enough to run fault-tolerant algorithms on 100-qubit logical qubits, a first for any hardware platform.' },
    { id: 'qu2', source: 'IBM Research Blog', time: '1d ago', kind: 'Roadmap', tone: 'calm', tag: 'IBM',
      title: 'IBM pushes 10,000 qubit Condor successor to 2028 roadmap',
      blurb: 'Yield and connectivity challenges on the 1,386-qubit Heron chip have slowed scaling. IBM says the delay allows improvements to interconnect architecture.' },
  ],
  space: [
    { id: 'sp1', source: 'Ars Technica', time: '1h ago', kind: 'Launch', tone: 'lead', tag: 'SpaceX',
      title: 'Starship Flight 9 reaches orbital velocity — first successful return burn',
      blurb: 'After two in-flight anomalies on earlier flights, Starship completed a controlled Pacific splashdown. Elon Musk confirmed launch cadence targets 12 flights in 2026.' },
    { id: 'sp2', source: 'Space News', time: '4h ago', kind: 'Satellite', tone: 'calm', tag: 'Starlink',
      title: 'Starlink Gen3 satellites achieve 4 Gbps per beam — doubles Gen2 capacity',
      blurb: 'SpaceX confirmed throughput gains from phased-array antenna redesign. The increase will allow maritime and aviation tiers to offer 500 Mbps consumer plans.' },
  ],
  health: [
    { id: 'he1', source: 'STAT News', time: '2h ago', kind: 'Clinical', tone: 'lead', tag: 'AI diagnostics',
      title: 'FDA clears AI tool that detects early pancreatic cancer from routine CT scans',
      blurb: 'Avenda Health\'s model spotted stage I/II tumors with 91% sensitivity, compared to 72% for radiologists alone. Rollout begins at 50 US cancer centers.' },
    { id: 'he2', source: 'Nature Medicine', time: '1d ago', kind: 'Research', tone: 'calm', tag: 'Biotech',
      title: 'AlphaFold 3 predicts RNA-protein interactions with near-crystallography accuracy',
      blurb: 'Google DeepMind\'s latest structure prediction model extends beyond proteins to RNA and DNA complexes, opening new drug-target discovery pipelines.' },
  ],
  cleantech: [
    { id: 'ct1', source: 'Bloomberg Green', time: '1h ago', kind: 'Energy', tone: 'lead', tag: 'Solar',
      title: 'Global solar capacity additions hit 700 GW in 2025 — double 2023 record',
      blurb: 'China accounted for 58% of new installations. Perovskite-silicon tandem modules crossed 30% efficiency in commercial production for the first time.' },
    { id: 'ct2', source: 'Reuters', time: '5h ago', kind: 'Policy', tone: 'calm', tag: 'Carbon',
      title: 'EU carbon price tops €120/tonne — record high drives industrial fuel switching',
      blurb: 'The ETS price surge is accelerating natural-gas-to-hydrogen transitions in steel and cement. Analysts expect €150 by year-end as supply tightens.' },
  ],
  xr: [
    { id: 'xr1', source: 'Road to VR', time: '3h ago', kind: 'Hardware', tone: 'lead', tag: 'Apple Vision',
      title: 'Apple Vision Pro 2 rumored with M4 Ultra and 8K micro-OLED displays',
      blurb: 'Supply-chain sources report Apple has ordered next-gen Sony micro-OLED panels and custom eye-tracking chips for a Q4 2026 launch at sub-$2,500 price point.' },
    { id: 'xr2', source: 'UploadVR', time: '6h ago', kind: 'Software', tone: 'calm', tag: 'Meta',
      title: 'Meta Horizon OS opens to third-party headsets — 4 OEMs confirmed',
      blurb: 'ASUS, Lenovo, and two undisclosed partners will ship Meta Horizon OS devices by mid-2026. The move mirrors Google\'s Android strategy for spatial computing.' },
  ],
  ipo: [
    { id: 'ip1', source: 'WSJ', time: '1h ago', kind: 'IPO', tone: 'lead', tag: 'Markets',
      title: 'Scale AI files S-1 — valued at $13.8B in last private round',
      blurb: 'The data-labeling giant targets a Nasdaq listing in Q3. Revenue grew 82% YoY to $1.4B, driven by US government and frontier lab contracts.' },
    { id: 'ip2', source: 'FT', time: '4h ago', kind: 'Markets', tone: 'calm', tag: 'Tech IPO',
      title: 'Databricks delays IPO to 2027, citing "no need for public capital"',
      blurb: 'CEO Ali Ghodsi told employees the company is profitable and prefers staying private while AI infrastructure spending remains buoyant.' },
  ],
  layoffs: [
    { id: 'la1', source: 'Layoffs.fyi', time: '2h ago', kind: 'Layoffs', tone: 'lead', tag: 'Tech',
      title: 'Intel cuts 3,400 more — total headcount down 22% since 2024',
      blurb: 'The latest round targets manufacturing and corporate functions. CEO Lip-Bu Tan framed the cuts as accelerating the "engineering-first" transformation.' },
    { id: 'la2', source: 'Business Insider', time: '5h ago', kind: 'Hiring', tone: 'calm', tag: 'AI jobs',
      title: 'AI engineers now command $500k+ total comp at top labs — up 40% in 12 months',
      blurb: 'While traditional software roles contract, demand for ML engineers, inference optimization, and RLHF specialists continues to surge, per Levels.fyi data.' },
  ],
  earnings: [
    { id: 'ea1', source: 'CNBC', time: '30m ago', kind: 'Earnings', tone: 'lead', tag: 'Big Tech',
      title: 'Alphabet Q1: Google Cloud hits $12.3B — AI products cited in 80% of calls',
      blurb: 'Alphabet beat estimates across all segments. CFO Anat Ashkenazi said Gemini integration in Search has raised query length and ad click-through rates.' },
    { id: 'ea2', source: 'SeekingAlpha', time: '3h ago', kind: 'Earnings', tone: 'calm', tag: 'NVIDIA',
      title: 'NVIDIA data center revenue: $36.8B — third consecutive record quarter',
      blurb: 'H200 and GB200 NVL72 drove sequential growth of 18%. Management guided Q2 at $43B±2%, well above the $38B consensus.' },
  ],
  robotics: [
    { id: 'ro1', source: 'IEEE Spectrum', time: '1h ago', kind: 'Research', tone: 'lead', tag: 'Humanoids',
      title: 'Figure 02 completes 4-hour autonomous car assembly shift at BMW plant',
      blurb: 'The humanoid robot performed 14 distinct tasks without human intervention, including torque gun operation and part transport. BMW plans to deploy 12 units by Q4.' },
    { id: 'ro2', source: 'TechCrunch', time: '4h ago', kind: 'Product', tone: 'calm', tag: 'Boston Dynamics',
      title: 'Boston Dynamics Atlas goes commercial — $250k per unit, 18-month backlog',
      blurb: 'Hyundai subsidiary opens Atlas orders to industrial customers globally. Early buyers include Toyota, DHL, and three undisclosed defense contractors.' },
  ],
  antitrust: [
    { id: 'an1', source: 'Reuters', time: '2h ago', kind: 'Legal', tone: 'lead', tag: 'Google',
      title: 'DOJ seeks Google search monopoly remedies — Chrome divestiture on table',
      blurb: 'Government lawyers proposed three structural remedies including forcing Google to divest Chrome or share its search index with rivals. Ruling expected Q4 2026.' },
    { id: 'an2', source: 'FT', time: '5h ago', kind: 'Antitrust', tone: 'calm', tag: 'Apple',
      title: 'EU orders Apple to allow third-party browser engines on iOS — €800M fine',
      blurb: 'The European Commission ruled that WebKit restrictions breach the DMA. Apple has 6 months to ship full engine support or face daily penalty payments.' },
  ],
  gdpr: [
    { id: 'gd1', source: 'IAPP', time: '1h ago', kind: 'Enforcement', tone: 'lead', tag: 'GDPR',
      title: 'TikTok fined €345M for CIPP violations involving minors\' data',
      blurb: 'Ireland\'s DPC found TikTok failed to apply privacy-by-default settings for under-18 accounts, exposing location and browsing data to third-party advertisers.' },
    { id: 'gd2', source: 'Euractiv', time: '4h ago', kind: 'Policy', tone: 'calm', tag: 'Data flows',
      title: 'EU-US adequacy decision renewed — but with sunset clause for 2028 review',
      blurb: 'The European Commission confirmed the Trans-Atlantic Data Privacy Framework remains valid, but added a mandatory 2028 review tied to US surveillance reform progress.' },
  ],
  exports: [
    { id: 'ex1', source: 'Bloomberg', time: '2h ago', kind: 'Policy', tone: 'lead', tag: 'Chips',
      title: 'BIS tightens AI chip export rules — H100 equivalent now requires license for 40 countries',
      blurb: 'The updated Entity List expansion targets chip procurement through third-party intermediaries in Southeast Asia. NVIDIA shares fell 4% on the news.' },
    { id: 'ex2', source: 'Politico', time: '5h ago', kind: 'Trade', tone: 'calm', tag: 'TSMC',
      title: 'TSMC halts advanced-node orders from three Chinese design firms',
      blurb: 'Following BIS guidance, TSMC suspended 3nm and below orders from firms with PRC military end-use connections, affecting ~$800M in annual revenue.' },
  ],
  digiinfra: [
    { id: 'di1', source: 'FT', time: '1h ago', kind: 'Infrastructure', tone: 'lead', tag: 'Undersea cables',
      title: 'Three undersea cables cut in Baltic — NATO activates critical infrastructure unit',
      blurb: 'Simultaneous outages on Baltic Sea cables connecting Finland, Estonia, and Sweden prompted NATO\'s new undersea infrastructure monitoring protocol.' },
    { id: 'di2', source: 'Euractiv', time: '4h ago', kind: 'Policy', tone: 'calm', tag: 'EU',
      title: 'EU Cyber Resilience Act enforcement begins — IoT makers must patch or face market ban',
      blurb: 'From June 1, connected devices sold in the EU must meet minimum patch-support requirements. An estimated 30% of current market devices remain non-compliant.' },
  ],
  cyberpol: [
    { id: 'cp1', source: 'CISA', time: '1h ago', kind: 'Policy', tone: 'lead', tag: 'Federal',
      title: 'CISA Secure by Design pledge reaches 300 software companies',
      blurb: 'Three hundred firms have now committed to eliminating default passwords, enabling MFA by default, and reducing entire classes of vulnerability. Critics say it\'s voluntary and toothless.' },
    { id: 'cp2', source: 'BBC', time: '3h ago', kind: 'Regulation', tone: 'calm', tag: 'UK',
      title: 'UK bans ransomware payments by public sector — NHS and councils included',
      blurb: 'The Home Office regulation, effective immediately, prohibits government bodies from paying ransomware demands. Insurers covering public-sector clients must also disclose payments.' },
  ],
  platform: [
    { id: 'pl1', source: 'Reuters', time: '2h ago', kind: 'Regulation', tone: 'lead', tag: 'DSA',
      title: 'X fined €600M under DSA for failing to curb illegal content recidivism',
      blurb: 'The European Commission found X repeatedly failed to action illegal content after initial takedowns. A compliance officer appointment is now mandatory.' },
    { id: 'pl2', source: 'The Guardian', time: '5h ago', kind: 'Policy', tone: 'calm', tag: 'TikTok',
      title: 'TikTok ban survives Supreme Court — ByteDance has 6 months to divest or shut US operations',
      blurb: 'The 9-0 ruling upheld the PAFACA law. ByteDance is in advanced talks with three US-based bidders; Microsoft, Oracle, and a PE consortium are the frontrunners.' },
  ],
}

export const TWEAKS_DEFAULTS = {
  palette: 'moss',
  displayFont: 'Instrument Serif',
  grain: 0.18,
  blur: 60,
  showSuggestions: true,
  compactMessages: false,
  tagline: 'Today in AI, gently unpacked.',
  newsFont: 'Bricolage Grotesque',
  preloadDemo: true,
}
