"""
Pydantic schemas — the wire format for user-facing API requests/responses.

These are deliberately separate from the SQLAlchemy ORM models in
app/models/. ORM models are how data lives on disk; Pydantic schemas are
how it travels over HTTP. Keeping them separate means:

  - We can change the DB shape without breaking clients (and vice versa).
  - Validation happens at the boundary, before any DB work.
  - The OpenAPI spec generated by FastAPI reflects the wire contract,
    not the DB internals.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, EmailStr, Field


# ─── Preferences ──────────────────────────────────────────────────────────
# Enum values come from docs/api.md §3.2 and docs/personas_and_features.md §3.
# Using `Literal[...]` gives us validation + OpenAPI enum docs for free.

Frequency = Literal["daily", "weekdays", "weekly"]
Length = Literal["short", "standard", "deep"]
Tone = Literal["technical", "business", "executive"]
DeliveryDay = Literal[
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"
]


class PreferencesIn(BaseModel):
    """Body shape for PUT /me/preferences."""

    # Tag selections — one list of tag slugs per taxonomy dimension.
    topics: list[str] = Field(default_factory=list)
    business_tags: list[str] = Field(default_factory=list)
    regulation_tags: list[str] = Field(default_factory=list)
    regions: list[str] = Field(default_factory=list)
    # Single-choice role tag; null if the user hasn't picked one.
    role: str | None = None
    muted_sources: list[str] = Field(default_factory=list)
    frequency: Frequency = "weekly"
    delivery_day: DeliveryDay = "monday"
    delivery_hour_local: int = Field(default=8, ge=0, le=23)
    length: Length = "standard"
    tone: Tone = "technical"
    language: str = Field(default="en", pattern=r"^[a-z]{2}$")


class PreferencesOut(PreferencesIn):
    """Returned shape — same as input today. Diverges later if we add server-derived fields."""
    pass


# ─── User ─────────────────────────────────────────────────────────────────


class UserOut(BaseModel):
    """Returned shape for GET /me."""

    # `from_attributes` lets us construct directly from a SQLAlchemy model:
    #   UserOut.model_validate(user_orm_instance)
    model_config = ConfigDict(from_attributes=True)

    id: str
    email: EmailStr
    display_name: str | None
    created_at: datetime
    last_login_at: datetime | None
